version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: node:12.4.0-alpine
    container_name: app
    restart: always
    depends_on:
     - db
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - .:/home/node/app
      - app_logs:/home/node/app/logs
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chatbot
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge

volumes:
  database-data:
  node_modules: 
  app_logs: